### ISSUE TITLE
Add Instrument Reviewer to Program page

### ISSUE THREAD

**Issue by mengesser** [spacetelescope/jwql#1003] opened 2022-07-26 20:09 UTC
The MIRI team has expressed that it would be useful to display who the instrument reviewer for a program is, in addition to the PC, as someone to direct questions and anomalies to as they come up in reviews.

**Comment by bhilbert4** [comment] 2022-07-26 20:11
Duplicate of #986

**Closed as completed by bhilbert4** 2022-07-26 20:11 UTC
Labels: enhancement
